from __future__ import annotations

"""Deterministic CAD export smoke for the Cell 3 right quick-release latch."""

import json
from pathlib import Path

import cadquery as cq

from .right_quick_release_latch import (
    RELEASE_TRAVEL_MM,
    RightQuickReleaseLatch,
    build_right_quick_release_latch,
)


def export_right_quick_release_latch(
    output_dir: str | Path,
    latch: RightQuickReleaseLatch | None = None,
) -> tuple[Path, ...]:
    latch = latch or build_right_quick_release_latch()
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)

    parts = (
        latch.socket,
        latch.tongue,
        latch.guide_capsule,
        latch.flexure_detent,
        latch.slider_and_grip,
        latch.continuous_withdrawal_sweep,
    )
    paths: list[Path] = []
    for part in parts:
        path = root / f"{part.part_id.lower()}.step"
        cq.exporters.export(part.solid, str(path))
        if not path.is_file() or path.stat().st_size <= 0:
            raise RuntimeError(f"failed to export positive STEP artifact for {part.part_id}")
        paths.append(path)

    # Export the already-controlled RELEASED_RESET_REQUIRED kinematic state as an
    # inspectable B-rep. The canonical manifest remains generated by the mechanism
    # object itself so package_sha256 continues to bind every manifest field.
    released_state_path = root / "right_latch_captive_slider_released_state.step"
    released_state = latch.slider_and_grip.solid.translate((RELEASE_TRAVEL_MM, 0.0, 0.0))
    released_shape = released_state.val()
    if not released_shape.isValid() or len(released_shape.Solids()) != 1:
        raise RuntimeError("released latch slider state must remain one valid solid")
    cq.exporters.export(released_state, str(released_state_path))
    if not released_state_path.is_file() or released_state_path.stat().st_size <= 0:
        raise RuntimeError("failed to export released latch slider state")
    paths.append(released_state_path)

    manifest_path = root / "right_quick_release_latch_manifest.json"
    manifest_path.write_text(
        json.dumps(latch.manifest(), sort_keys=True, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    paths.append(manifest_path)
    return tuple(paths)
